name: Deploy to Google Cloud Storage (Two Buckets)

on:
  push:
    branches:
      - main  # Change this if you want to deploy from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 4: Sync files to root domain bucket (example.com)
      - name: Sync to root domain bucket
        run: |
          gsutil rsync -r ./ gs://${{ secrets.GCP_BUCKET_ROOT }}

      # Step 5: Sync files to www subdomain bucket (www.example.com)
      - name: Sync to www subdomain bucket
        run: |
          gsutil rsync -r ./ gs://${{ secrets.GCP_BUCKET_WWW }}
